### ISSUE TITLE
[1.18.2 Bug] C+ Netherrack in Overworld

### ISSUE THREAD

**Issue by itsdinkd** [ConsistencyPlus/ConsistencyPlus#110]
[**Describe the bug:**
C+ Netherrack is generating in mineshafts

**Versions:**
Minecraft version: 1.18.2
C+ version: .5.0
Fabric API / QSL / Forge version: 51.1

**To Reproduce:**
1. Visit Mineshafts

**Expected behavior:**
No Netherrack in overworld

**Screenshots:**
![image](https://user-images.githubusercontent.com/35115304/166162289-15f6f38f-1b02-4ca0-9d6d-e3812bc88b04.png)

**Comment by Cart3r1234** [comment]
Looks to maybe be some sort of worldgen incompatibility?  Consistency+ doesn't touch anything related to worldgen at all, but looking at the screenshot it seems you have other mods installed that do.  Please attach a log so we can investigate further.

**Comment by itsdinkd** [comment]
> Looks to maybe be some sort of worldgen incompatibility? Consistency+ doesn't touch anything related to worldgen at all, but looking at the screenshot it seems you have other mods installed that do. Please attach a log so we can investigate further.

I do use terrablender so maybe? 

https://gist.github.com/itsdinkd/e6d3076f3a0bc1cdcf968311e1a2a278

**Comment by Siuolthepic** [comment]
Can you give a specific world seed?

**Comment by Cart3r1234** [comment]
From the log:
> [10:12:03] [main/INFO]: Loading 501 mods

If possible, could you do a binary split (split the modpack in half, test each half with C+, get rid of the half that works fine, then repeat until you've found the exact mod that causes it) with the pack to find which specific mod causes it?  With 500 mods it would take about 9 tests to go through the entire pack this way

**Comment by itsdinkd** [comment]
> Can you give a specific world seed?

-7964943223422234

**Comment by Cart3r1234** [comment]
Coordinates for the mineshaft in the screenshot would be helpful.  I explored a few mineshafts on that seed but didn't find anything broken,

**Comment by Cart3r1234** [comment]
Reviewing the log, it appears that this was on a multiplayer server, which is something we missed before.  Examining the screenshot closer, it seems like someone just dug a tunnel and placed them there manually.  

I'm going to close this because that seems to be the case, but will reopen if you can prove it happens in singleplayer.  The best way to go about this would be to generate a world of that seed with the same modpack and then check these coordinates in a singleplayer world, and provide a screenshot.
