### ISSUE TITLE
Support for Colored Lights

### ISSUE THREAD

**Issue by fatpowaranga** [ConsistencyPlus/ConsistencyPlus#114]
**Feature:**

I thought it would be cool for all the colored glowstones (and other blocks that might glow?) to actually glow the color they are. Not sure if it would be something ConsistencyPlus itself would implement or maybe some addon to ConsistencyPlus, but thought i'd post this here :)

**Alternatives:**

**Additional info:**

Link to Colored Lights on Modrinth: https://modrinth.com/mod/colored-lights

**Comment by Cart3r1234** [comment]
![image](https://user-images.githubusercontent.com/69820300/170850964-87e18451-5e44-4a8b-8d76-1c34bcf59b3f.png)
Seems like an easy thing to implement, and would be a cool thing to have integration for.  We'll look into it!

**Comment by Cart3r1234** [comment]
![image](https://user-images.githubusercontent.com/69820300/173506658-0a55830a-b587-4700-afb2-48cf162c8be7.png)

Its not very noticeable on a lot of our blocks since most don't emit full light (crying obsidian only emits light level 9), but I got it working.  Will be part of our next release.  Works pretty well with dyed glowstone.
