### ISSUE TITLE
Give Bamboo some Love

### ISSUE THREAD

**Issue by ardissaps** [ConsistencyPlus/ConsistencyPlus#116]
**Feature:**
Bamboo Fence, Wall, Gate, Door, Step(or Stair), Boat, etc in original green or non striped version.

**Comment by Cart3r1234** [comment]
Currently, the only planned bamboo-related feature is a full block similar to hay bales to be used as decoration and/or storage.
Not having a wood-like block set for bamboo isn't really something that would be considered an inconsistency, mainly due to there not really being any other non-tree crops that can be directly made into wood-like building materials via crafting.  Chorus plants -> purpur is the only one that really comes close, but is more of a special case in comparison.

While these features may not be a good fit for Consistency+, you might be interested in [this mod](https://www.curseforge.com/minecraft/mc-mods/bamboo-tweaks) - it adds pretty much everything you listed, and more.  The only downside is that it seems to have been abandoned on 1.17, and does not support newer minecraft versions.
