### ISSUE TITLE
Raw metal blocks

### ISSUE THREAD

**Issue by DerangedPenguins** [ConsistencyPlus/ConsistencyPlus#120]
Could you add raw copper oxidization, and for the new gold and iron stuff add raw block types like that too.

**Comment by Cart3r1234** [comment]
We did consider making changes to raw metal blocks when planning how we were going to do the copper sets (and when we eventually work with the other metals), but currently it is not something we are going to add.  It would likely involve changes to the vanilla textures, which we try to avoid whenever possible - Both the raw copper block and item have some parts which are clean, and others that are fully oxidized, rather than spots that contain partially oxidized bits like smelted copper blocks have.  We would also have to add new items for the other 7 (4 stages + waxed) raw metal items that would be the result of uncrafting said blocks.
