### ISSUE TITLE
Having C+ installed causes blocks from Minekea to have untranslated names

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [ConsistencyPlus/ConsistencyPlus#132]
**Describe the bug:**

When C+ is installed together with Minekea, Minekea's blocks have broken/untranslated names.

**Versions:**

Minecraft version: 1.19.2
C+ version: 0.5.1
Fabric API / QSL / Forge version: 0.61.0 / 4.0.0-beta.11

**Other mods:**

[Minekea](https://www.curseforge.com/minecraft/mc-mods/minekea-fabric): 3.3.3

**Logs:**

https://gist.github.com/Footage2-Amply-Pounce/cb3f7fd508e37ffcaccd87aeee5cd5e8

**To Reproduce:**

1. Install both mods and its' dependencies
2. Load into a world and look up some blocks from Minkea, e.g. bookshelf stairs/vertical stairs

**Expected behavior:**

Proper names for all blocks.

**Screenshots:**

![2022-09-12_03 43 23](https://user-images.githubusercontent.com/86702831/189559972-da8c5f3f-8514-4edd-be5e-bffed2c9fe19.png)

**Additional info:**

I've previously reported a similar issue between Minekea and Better Biome Blend here: https://github.com/chimericdream/minekea-fabric/issues/67. Minekea has a duplicate set of blocks for the cobbled endstone, I usually disable it, but this test was made with default configs for all mods; the issue is reproducible with or without cobbled endstone.

**Comment by Cart3r1234** [comment]
Made a comment about it here (https://github.com/chimericdream/minekea-fabric/issues/67), if I had to guess its probably because we have a lang file in the minecraft namespace so that we can change a few of the vanilla translations.

**Comment by Cart3r1234** [comment]
Closing this as it seems to be an issue on Minekeas end with how it handles modded translations in the minecraft namespace.  Will reopen if anything changes that required attention on our end.

**Comment by Footage2-Amply-Pounce** [comment]
Yep, thanks for the hint. I now also know what renamed glowing inc sacs to glowing dye, as I didn't like that :D

**Comment by Footage2-Amply-Pounce** [comment]
Hello again, I've came across another mod that modifies vanilla translation strings ([Variant Lanterns](https://www.curseforge.com/minecraft/mc-mods/variant-lanterns-fabric)), but I noticed that their lang file was not in `minecraft` namespace despite that. So I simply moved C+ stuff out of `minecraft` into its own folder (had to manually merge the lang file) and voila, the issue went away.

Is there a reason for those files to be in `minecraft` instead of its own folder?

**Comment by Cart3r1234** [comment]
If I remember correctly we moved them to the minecraft namespace because in some cases the translations didn't apply when in our namespace (at some point we also ran into an issue where translations were being applied differently in dev environments than they were in production). 

We originally did have them in the Consistency+ namespace (see [here](https://github.com/ConsistencyPlus/ConsistencyPlus/issues/24), which was from before we moved them), but moved them to the minecraft namespace afterwards to resolve the issues of them not applying correctly.  

Its possible that whatever problem was occurring that led us to moving them no longer exists or has been resolved in other ways, in which case we probably should move them back to the lang files in our namespace.
