### ISSUE TITLE
LANG file issues server side

### ISSUE THREAD

**Issue by MissGamerz** [ConsistencyPlus/ConsistencyPlus#134]
**Describe the bug:**
your mod breaks default minecraft lang on servers 

**Versions:**
Minecraft version: 1.19.2
C+ version: 0.5.1
QSL

**Suggested Fix**
Move your stuff from */assets/minecraft/lang/en_us.json* to */assets/consistency_plus/lang/en_us.json

ive done this in my copy and it worked fine

**Comment by Cart3r1234** [comment]
> ive done this in my copy and it worked fine

![image](https://user-images.githubusercontent.com/69820300/193641614-4a31dce6-9d56-47f4-b225-a68c641f0b88.png)
I tried it out and our translations don't get applied when they're in our namespace.  "Bricks" is supposed to be replaced by "Terracotta Bricks," and having the vanilla string change in the consistency_plus namespace doesn't properly apply it.  This screenshot is taken in production, so its not just a dev env issue.

**Comment by MissGamerz** [comment]
huh interesting i didnt notice the renaming of vanilla blocks, which yea that wouldnt work but somehow something consistancy+ is breaking lang files i cant seem to find the issue other than that, this appears to be in server enviroments only though and in client only enviroments it works fine...

**Comment by Cart3r1234** [comment]
> huh interesting i didnt notice the renaming of vanilla blocks

All of the strings in the minecraft namespaced lang file are ones that override vanilla blocks, which is why they were separated into their own file.  
What specific lang/mods break when using C+ on a server?  I suspect there's a larger issue here than it seems, because having certain block/item strings in a minecraft namespaced lang file shouldn't be causing issues with mods that don't also modify those specific strings.  More details will definitely help in figuring this out - 
* Does it happen with all mods?
* For the mods it affects, does it break the modded strings, modified vanilla strings from that mod, or both?

> do you have discord?

We do have a discord (https://discord.gg/VeNX7h8bAK) if you want to talk with us about the issue there.

**Comment by MissGamerz** [comment]
yea ive join ping me its easier on there than on here maybe i can show you aswell with screenshare or something?

**Comment by Cart3r1234** [comment]
Interesting.  I tried in both the dev env and a production build and the vanilla strings weren't properly overwritten when merging them, and only worked when the translations were in the minecraft namespace. 
We haven't solved the issue yet, but we did discuss it some in the #translations channel in our discord.

**Comment by TropheusJ** [comment]
the vanilla changes have been moved to a built-in pack. They will not apply on servers, and fabric clients can disable it if needed. Forge clients cannot disable it as forge has a much more limited API for built-in packs, and I don't think this occurs on Forge. If it does, let us know.
