### ISSUE TITLE
Netherite Stairs take an eternity to mine

### ISSUE THREAD

**Issue by ghost** [ConsistencyPlus/ConsistencyPlus#139]
Netherite stairs take forever to mine even with an netherite pickaxe

**Comment by Cart3r1234** [comment]
This is likely because netherite stairs are not part of the pickaxe.json block tag.  Currently they just exist as a joke block (a reference to one of Mojang's past april fools updates where they were added as an easter egg), however netherite will get a full set of blocks at some point.  Will fix next update.

**Comment by Cart3r1234** [comment]
Fixed as of latest commit, will close when we release the next update.

**Comment by Cart3r1234** [comment]
Closing this now since its been fixed for a while and the next update is being worked on.
