### ISSUE TITLE
How beta are your betas?

### ISSUE THREAD

**Issue by allanonmage** [ConsistencyPlus/ConsistencyPlus#177]
A lot of devs live by the perpetual beta lifestyle, probably due to influence by lawyers from corporate-land and their day jobs.  I'm checking on the mods in my modpack, and see that the 1.19.4 mod is listed as beta on Modrinth.  Did you migrate to a perpetual beta lifestyle, or are they not yet ready for deployment?

**Comment by Cart3r1234** [comment]
0.5.2 is currently in beta because it is not finished.  If you look at our last major release, 0.5.1, you will see that it is not marked as Beta, and has a full release version.  0.5.2 will have full release versions once all of the critical bugs are fixed and everything we plan on having in the version is complete.
