### ISSUE TITLE
Lang file contains vanilla strings?

### ISSUE THREAD

**Issue by RDKRACZ** [ConsistencyPlus/ConsistencyPlus#23]
So I wanted to make a translation but was confused when I saw this https://github.com/ConsistencyPlus/ConsistencyPlus/blob/master/src/main/resources/assets/consistency_plus/lang/en_us.json#L5.

**Comment by DragonEggBedrockBreaking** [comment]
This is because it changes the name of the vanilla item, probably intentionally.

**Comment by Siuolthepic** [comment]
Yes, we contain them intentionally, for two reasons.

1. Redefining certain blocks.
 In some situations, such as Purpur (Minecraft) -> Cut Purpur (Consistency+), we decided that the vanilla block fits better in a different category (Such as Cut.). So since we want structures that both generate and/or were player made prior to using this mod to retain the same look. We decided to simply change what lang said blocks use.
 
 2. Consistency on Names
 In other situations, such as Red Nether Bricks -> Crimson Nether Bricks, we wanted to remain consistent on the lang side. And as such, we decided to use those langs.
 
 Im gonna close this for now, but if theres more questions you can open it or talk to us on discord.
 Sorry if Im not making too much sense or am rude btw, low sleep does that to ya.
