### ISSUE TITLE
ConsistencyPlus adds Purpur Block even though it already exists?

### ISSUE THREAD

**Issue by RDKRACZ** [ConsistencyPlus/ConsistencyPlus#24]
There is `minecraft:purpur_block` and `consistencyplus:purpur_block`

**Comment by DragonEggBedrockBreaking** [comment]
Minecraft purpur was renamed to cut purpur:
https://github.com/ConsistencyPlus/ConsistencyPlus/blob/201e38eaeedf44ee1a7525486a9d605b92a238de/src/main/resources/assets/consistency_plus/lang/en_us.json#L9

and a new purpur block was added:
https://raw.githubusercontent.com/ConsistencyPlus/ConsistencyPlus/master/src/main/resources/assets/consistency_plus/textures/block/purpur_block.png

**Comment by Siuolthepic** [comment]
Yes, like DragonEgg said, the Purpur block added by Minecraft is changed to be the Cut Purpur block in Consistency+

Some people may ask "Why dont you just change the texture" which is a valid argument, however, we didnt want to change how structures from vanilla, other mods, and player made ones looked. 

Theres more blocks that do a similar thing, it IS intentional, so Ill close this issue, if you have more questions, feel free to talk about it in discord or in discussion.
