### ISSUE TITLE
[1.16.5] Recipe achievements spam.

### ISSUE THREAD

**Issue by ghost** [ConsistencyPlus/ConsistencyPlus#95]
**Describe the bug**
after joining the game, the player receives all the recipes.

**Versions**
Minecraft version: 1.16.5
C+ version: 0.4.3
Fabric API version: 42

**To Reproduce**

1. Create a world

![2022-01-13_00 53 16](https://user-images.githubusercontent.com/88648036/149241366-3e5d4df6-eb59-4262-8cb3-a48264989165.png)
![2022-01-13_00 53 17](https://user-images.githubusercontent.com/88648036/149241369-917c2e5d-b000-4c5d-9491-d7c62fd2d19c.png)
**Screenshots**

**Comment by Cart3r1234** [comment]
This is fixed for 0.5.0; recipe advancements were pretty messed up from 0.3.x-0.4.x but we finally got them working correctly in the upcoming 0.5.0 release candidate.  We still don't know what was causing them to all be granted upon world join, as that wasn't intentional (at least I don't think it was, I don't really remember that being planned)
Either way, this will be fixed for 0.5.0, but thanks for the report!  We'll leave it open until we release the update in a few days though.

**Comment by cssmc** [comment]
thanks
