### ISSUE TITLE
Cobbled_X skipping furnaces

### ISSUE THREAD

**Issue by scribbler957** [ConsistencyPlus/ConsistencyPlus#98]
v0.5.0-RC1
There are a bunch of recipes that bypass the vanilla smelt cobble mechanic. (i.e., 2x2 cobble to get stone instead of using the furnace.)

**Comment by Cart3r1234** [comment]
This is intentional.  The 2x2 recipe is intended as an early game solution, as it is crafted with a 4:1 ratio rather than 1:1 for smelting, meaning its faster but you don't get as much out of the recipe.  Cobblestone being cuttable in stonecutters is also intentional as part of the QOL changes Stonecutter Recipe Tags provide (being able to cut any block into any other of that material type)

**Comment by scribbler957** [comment]
Would you consider a config option? With a couple other mods adding alternate cobble/stone the stonecutter seems overcrowded.

**Comment by Cart3r1234** [comment]
It is currently something we plan on making configurable once we add a config, however it will likely be a few updates before it is implemented, as we have more extensive plans for the config besides loot table and recipe stuff.  I may make a datapack to revert these changes at some point though, as they're all things that could be easily changed via datapack.
