### ISSUE TITLE
Consistency+ Main - Finished initialization process crash

### ISSUE THREAD

**Issue by Elliegobrr** [ConsistencyPlus/ConsistencyPlus#99]
Should specify it doesn't crash the game, but locks it up when starting the game about 80% of the time.

**Comment by TropheusJ** [comment]
we can't do anything without a log file.

**Comment by Cart3r1234** [comment]
Any information at all helps.  Minecraft version, C+ version, which loader you're using/loader version, a video, other mods you're using, etc.  Just saying it locks up on launch doesn't help us much in figuring it out because we don't know what we're looking at/for.  Please add more information sometime soon (within the next few days) or this issue will be closed.

**Comment by TropheusJ** [comment]
and a log has all of that info in it.
